// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQPtyMmRb9izpq3yzjMdTfzQpDbMFq3E',
    appId: '1:244156996836:web:aba32899fe84f1defb20f1',
    messagingSenderId: '244156996836',
    projectId: 'skynte-fcbcd',
    authDomain: 'skynte-fcbcd.firebaseapp.com',
    storageBucket: 'skynte-fcbcd.appspot.com',
    measurementId: 'G-ZZKMYTY9BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfS9_QuXWFQhTpjSiJ-gmsOS7IpnJXIOo',
    appId: '1:244156996836:android:26e8ae1461da155efb20f1',
    messagingSenderId: '244156996836',
    projectId: 'skynte-fcbcd',
    storageBucket: 'skynte-fcbcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqhm1ZBFwkaVulrjJz8UVyQl7Kuwe6AkQ',
    appId: '1:244156996836:ios:04594a0aa860ca0dfb20f1',
    messagingSenderId: '244156996836',
    projectId: 'skynte-fcbcd',
    storageBucket: 'skynte-fcbcd.appspot.com',
    iosClientId: '244156996836-79kchr7r10f2qnqln9b81v58dnmg38li.apps.googleusercontent.com',
    iosBundleId: 'de.skyface753.skynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqhm1ZBFwkaVulrjJz8UVyQl7Kuwe6AkQ',
    appId: '1:244156996836:ios:04594a0aa860ca0dfb20f1',
    messagingSenderId: '244156996836',
    projectId: 'skynte-fcbcd',
    storageBucket: 'skynte-fcbcd.appspot.com',
    iosClientId: '244156996836-79kchr7r10f2qnqln9b81v58dnmg38li.apps.googleusercontent.com',
    iosBundleId: 'de.skyface753.skynote',
  );
}
